#!/usr/bin/env bash

   fldlist_lmon="ALT AR BTRAN CH4PROD DENIT EFLX_LH_TOT ELAI ER ESAI FAREA_BURNED \
    FCEV FCH4 FCH4TOCO2 FCOV FCTR FGEV FGR FGR12 FH2OSFC FINUNDATED FIRA FIRE FLDS FPG FPI \
    FPSN FROST_TABLE FSA FSAT FSDS FSH FSM FSNO FSR F_DENIT F_NIT GPP \
    GROSS_NMIN H2OSFC H2OSNO HR HTOP LAND_USE_FLUX LEAFC FROOTC NDEP_TO_SMINN NBP NEE NEP \
    NET_NMIN NFIX_TO_SMINN NPP Q2M QCHARGE QDRAI QOVER QRUNOFF QRGWL QSNOMELT \
    QSOIL QVEGE QVEGT RAIN RH2M SMIN_NO3 SMIN_NH4 SNOW SNOWDP SNOWICE SNOWLIQ SNOW_DEPTH \
    SNOW_SINKS SNOW_SOURCES SOMHR TG TSA TREFMXAV TREFMNAV TSAI TLAI TV QBOT TBOT \
    AGNPP FROOTC_ALLOC LEAFC_ALLOC WOODC_ALLOC WOOD_HARVESTC \
    CH4_SURF_AERE_SAT CH4_SURF_AERE_UNSAT CH4_SURF_DIFF_SAT \
    CH4_SURF_DIFF_UNSAT CH4_SURF_EBUL_SAT CONC_CH4_SAT \
    CONC_CH4_UNSAT FCH4_DFSAT MR TOTCOLCH4 ZWT_CH4_UNSAT \
    FSDSND FSDSNI FSDSVD FSDSVI \
    TWS VOLR WA ZWT_PERCH ZWT WIND COL_FIRE_CLOSS \
    F_DENIT_vr F_NIT_vr H2OSOI O_SCALAR SOILICE SOILLIQ SOILPSI TLAKE TSOI T_SCALAR W_SCALAR  \
    SOIL1N SOIL2N SOIL3N SOIL1C SOIL2C SOIL3C TOTVEGC TOTVEGN TOTECOSYSC TOTLITC TOTLITC_1m \
    TOTLITN_1m TOTSOMC TOTSOMC_1m TOTSOMN_1m CWDC PBOT QSNWCPICE CWDC QRUNOFF TOTPRODC SNOBCMCL LIVESTEMC CPOOL DEADSTEMC SOILC \
    PCT_CFT LIVECROOTC LITR1C_TO_SOIL1C LITFALL DEADCROOTC QINTR LITR2C_TO_SOIL2C \
    PCT_NAT_PFT PCT_LANDUNIT LITR3C_TO_SOIL3C GR LEAFC_ALLOC SOILWATER_10CM"

   #LS3MIP variables
   fldlist_lmon+=" SNOWLIQ MR SOILICE CWDC QRUNOFF SOILLIQ TOTPRODC SNOBCMCL TOTVEGC \
                 LIVESTEMC GPP FAREA_BURNED SOIL2C CPOOL DEADSTEMC SOILC TSOI NEP \
                 SOIL3C WOODC_ALLOC QVEGE PCT_CFT FROOTC_ALLOC SOILWATER_10CM FSNO \
                 LIVECROOTC SNOWICE COL_FIRE_CLOSS LITR1C_TO_SOIL1C LITFALL TLAI \
                 TOTLITC QSOIL SNOWDP DEADCROOTC LAND_USE_FLUX QOVER NPP QVEGT NBP \
                 QSNWCPICE QINTR HR LITR2C_TO_SOIL2C PCT_NAT_PFT WOOD_HARVESTC LEAFC \
                 PCT_LANDUNIT SOIL1C LITR3C_TO_SOIL3C GR QSNOMELT AR LEAFC_ALLOC H2OSNO_TOP"
   fldlist_lmon+=" H2OSNO_TOP"
   fldlist_lmon+=" TWS"
   fldlist_lmon+=" SNODSTMSL SNOOCMSL FGR NEE COL_FIRE_CLOSS TOTPRODC SNOW RAIN PBOT TREFMXAV TREFMNAV TSA TG Q2M \
                  RH2M TAUX TAUY FSH FSR FSDS FLDS FIRE WIND EFLX_LH_TOT"
   fldlist_lmon+=" SNOBCMSL"
   fldlist_lmon+=" FROOTC"
   fldlist_lmon+=" topo"
   fldlist_lmon+=" SOIL4C"

   fldlist_lmon+=" QSNWCPICE CWDC QRUNOFF TOTPRODC SNOBCMCL LIVESTEMC CPOOL DEADSTEMC SOILC \
                PCT_CFT LIVECROOTC LITR1C_TO_SOIL1C LITFALL DEADCROOTC QINTR LITR2C_TO_SOIL2C \
                PCT_NAT_PFT PCT_LANDUNIT LITR3C_TO_SOIL3C GR LEAFC_ALLOC"

   fldlist_amon="PRECSC PRECSL TREFHT TREFHTMN TREFHTMX RHREFHT CO2 SHFLX LHFLX QFLX PRECC PRECL FLDS FLNS FSDS FSNS"
   fldlist_amon+=" SHFLX LHFLX QFLX PRECC PRECL FLDS FLNS FSDS FSNS"
   fldlist_amon+=" PRECSC PRECSL"
   fldlist_amon+=" TREFHT TREFHTMN TREFHTMX RHREFHT"
   fldlist_amon+=" PRECSC PRECSL TREFHT TREFHTMN TREFHTMX RHREFHT CO2 SHFLX LHFLX QFLX PRECC PRECL FLDS FLNS FSDS FSNS SFCO2 SFCO2_LND SFCO2_OCN SFCO2_FFF \
      FLUT FLUTC FSNT FSNTC FLNT FLNTC SOLIN FSNTOA FSNTOAC FSUTOA FSUTOAC LWCF PBLH CLDTOT CLOUD SWCF TGCLDCWP TGCLDIWP TGCLDLWP CLDHGH CLDLOW CLDMED"




   echo $fldlist_lmon

   echo 
   echo $fldlist_lmon | tr ' ' '\n' | sort -u | xargs > Lmon_cmor.txt


   newfld=`echo $fldlist_lmon | tr ' ' '\n' | sort -u | xargs`

   echo; echo

   echo $fldlist_lmon

   echo 'yyy'
   echo $fldlist_amon | tr ' ' '\n' | sort -u | xargs  > Amon_cmor.txt


   #-echo 'xxx'
   #-name=$(<"lmon_cmor.txt")
   #-echo $name

   #-vars="$(echo -e "${name}" | sed -e 's/ \+/,/g' | sed -e 's/,$//')"

   #-echo $vars > aaa
